apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability
  template:
    metadata:
      labels:
        app: observability
    spec:
      containers:
        - name: observability
          image: grafana/otel-lgtm:latest # Use the appropriate image tag if necessary
          ports:
            - name: grafana
              containerPort: 3000
            - name: grpc
              containerPort: 4317
            - name: http
              containerPort: 4318
          env:
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: observability
spec:
  selector:
    app: observability
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    cilium.io/public-ip: "true"
  annotations:
    "io.cilium/lb-ipam-sharing-key": "0000"
spec:
  selector:
    app: observability
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

